name: Golshah Agdasi
favicon: null
layout_spectrum: 0.3104410523083061
typography_spectrum: 0.8613127581775188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5777327443938702
  lightness: 0.06885569682344794
  saturation: 0.2143229644279927
  rhythmicContrast: 0.10021687927655876
purpose: []
